#ifndef __CITY_AUTO_H
#define __CITY_AUTO_H
#include "define.h"
#include "server_structsend_auto.h"
struct _city {
//--Automatically generated
				int actorid;	//角色ID
				int index;	//索引
				char name[22];	//名称
				char type;	//城池类型
				char shape;	//领主形象(选取)
				int headid;	//领主头像(自定义)
				short country;	//选择的国家(真实)
				char ipcountry[3];	//IP地址所在国家
				char language;	//选择语言
				char os;	//系统1ios 2android 3win
				char platid;	//平台
				int createtime;	//创建时间
				int lastlogin;	//上次登陆时间
				int lastlogout;	//上次登出时间
				char state;	//城池当前状态
				short posx;	//位置
				short posy;	//位置
				int sflag;	//标志位
				short level;	//玩家等级
				int exp;	//玩家经验
				char viplevel;	//VIP等级
				int vipexp;	//VIP经验
				char nation;	//国家(魏蜀吴)
				char official;	//官职
				char place;	//爵位
				char zone;	//区域
				int battlepower;	//战力
				int battlepower_hero;	//英雄提供战力
				int battlepower_equip;	//装备提供战力
				int battlepower_tech;	//科技提供战力
				int battlepower_nequip;	//国器提供战力
				int battlepower_place;	//爵位提供战力
				int battlepower_girl;	//女将提供战力
				char mokilllv;	//击杀野怪最高级别
				short body;	//体力
				short bodysec;	//体力恢复时间(每秒-1)
				int silver;	//银币
				int wood;	//木材
				int food;	//粮草
				int iron;	//镔铁
				unsigned char levynum;	//当前征收次数
				short levysec;	//下次征收时间(每秒-1)
				int people;	//人口
				int prestige;	//威望值
				int friendship;	//友谊积分
				int function;	//功能是否开启
				char equip_washnum;	//装备洗练免费次数
				short equip_washsec;	//装备下次免费洗练时间
				short forgingkind;	//打造装备种类
				int forgingsec;	//打造剩余时间
				char hero_washnum;	//英雄洗练次数
				short hero_washsec;	//英雄下次洗练免费时间
				char autobuild;	//自动建造剩余次数
				char autobuildopen;	//自动建造是否开启
				int ptsec;	//城池保护状态剩余时间
				short peoplesec;	//城池人口回复时间
				int eventsec;	//事件倒计时
				short questid[16];	//任务ID
				int questvalue[16];	//任务数值
				char techlevel[40];	//科技
				char techprogress[40];	//科技进度
				int data_record[16];	//数据记录
				char matkind[8];	//材料生产kind
				char matnum[8];	//材料生产数量
				int matsec[8];	//材料已经生产时间
				char matquenum;	//材料生产队列数量
				char matkind_will[8];	//材料预定生产kind
				char matnum_will[8];	//材料预定生产数量
				char matkind_over[8];	//材料生产完毕
				char matnum_over[8];	//材料生产完毕
				int hv_fcd;	//良将寻访免费CD
				int hv_hsec;	//神将寻访解锁时长
				char hv_hf;	//神将寻访免费次数
				char kw_co;	//恭贺是否完毕
				short kw_px;	//挖宝坐标
				short kw_py;	//挖宝坐标
				char kw_tn;	//挖宝第几次
				char kw_has;	//挖宝已经挖到图纸
				int kw_totalkill;	//本次血战累杀
				int kw_point;	//血战总击杀
				short rb_num;	//重建家园次数
				int rb_silver;	//给予的重建家园资源
				int rb_wood;	//给予的重建家园资源
				int rb_food;	//给予的重建家园资源
				short rb_df;	//给予的重建家园资源
				short neq_lv[6];	//国器等级
				char neq_exp[6];	//国器经验
				char neq_pro[6];	//国器改造的进度次数
				int neq_sec[6];	//国器升级或改造时间
				char neq_star[6];	//国器改造星级
				short guardsec;	//城墙守卫冷却时间
				CityGuard guard[30];	//城墙守卫
				Hero hero[12];	//上阵英雄
				CityNationHero nation_hero[15];	//国家名将信息
				Building building[6];	//普通建筑
				BuildingBarracks building_barracks[4];	//兵营建筑
				BuildingRes building_res[64];	//资源建筑
				char worker_op;	//建造队列操作
				int worker_sec;	//建造剩余时间(每秒-1)
				char worker_kind;	//当前升级建筑类型
				char worker_offset;	//当前升级建筑索引
				char worker_free;	//是否使用过免费
				char worker_op_ex;	//建造队列操作(商用)
				int worker_sec_ex;	//建造剩余时间(每秒-1)(商用)
				char worker_kind_ex;	//当前升级建筑类型(商用)
				char worker_offset_ex;	//当前升级建筑索引(商用)
				char worker_free_ex;	//是否使用过免费
				int worker_expire_ex;	//商用建造队列到期时间
				int wnsec;	//建造队列所需时间
				int wnsec_ex;	//建造队列所需时间
				int wnquick;	//建造队列奖励的加速
				int wnquick_ex;	//建造队列奖励的加速
				short ofkind[3];	//建筑官员种类
				int ofsec[3];	//建筑官员剩余秒
				int offree[3];	//建筑官员免费情况
				int ofquick[3];	//建筑官员已经使用的加速时间
				char signature[128];	//个性签名
				short wcard;	//周卡天数
				short mcard;	//月卡天数
				short bag_gid[8];	//推送的礼包
				int bag_time[8];	//推送的礼包剩余时间
				char bag_num[8];	//推送的礼包剩余次数
				int buffsec[8];	//buff
				char atgu;	//城防补充次数
				char atgu_op;	//城防补充是否开启
				short nation_qv[3];	//国家任务数值
				short nation_rankv[3];	//国家每周的排行榜数值
				short vote;	//选票数
				char ballot;	//是否投票
				short tokenballot;	//元宝拉票票数
				int soldiers[3];	//兵力
				char tc_level[2];	//天策府科技等级
				char tc_progress[2];	//天策府科技进度
				short bufftrain;	//武卒官加速值
				int teacherid;	//师父
				short act06_state;	//全服返利领取状态
				char robot_ai;	//AI
				int robot_cd;	//机器人逻辑
				char edevent[16];	//政务系统
				short edevent_sec;	//政务系统
				char edevent_num;	//政务系统
				SLK_NetS_CityEvent city_event[4];	//城内事件
				SLK_NetS_BattleEvent battle_event[4];	//军事事件
				CityAttr attr;	//属性加成
				int actor_index;	//角色索引
				int unit_index;	//显示索引
				int battle_armyindex[8];	//出征部队
				int underfire_armyindex[8];	//目标部队（暂别用）
				int help_armyindex[32];	//协防部队
				int mapevent_index[6];	//地图事件
				int underfire_groupindex[16];	//目标集结索引
				int zoneunit_index;	//地区显示索引
				short own_townid;	//哪个城的城主
				int temp_silver;	//临时存资源
				int temp_wood;	//临时存资源
				int temp_food;	//临时存资源
				char guardnum;	//城墙守卫数量
				int rank_server;	//全服排行榜排名
				int rank_zone;	//区域排行榜排名
				int rank_nation;	//国家排行榜排名
				int battlepower_building;	//建筑提供战力
				int temp_wounded_soldiers[3];	//临时伤兵
				char mapcall;	//地图召唤
				Girl girl[80];	//女将
};
typedef struct _city City;

typedef City * (*LPCB_GETCITY)( int index );
typedef int (*LPCB_LOADCITY)( int index );
int city_load_auto( LPCB_GETCITY pCB_GetCity, LPCB_LOADCITY pCB_LoadCity, const char *pTab );
int city_save_auto( City *pCity, const char *pTab, FILE *fp );

#endif
