CREATE TABLE `army` (
  `index` int(11) NOT NULL DEFAULT '0' COMMENT '部队索引',
  `id` int(11) NOT NULL DEFAULT '0' COMMENT '部队唯一ID,合法性验证',
  `state` tinyint(4) NOT NULL DEFAULT '0' COMMENT '状态',
  `statetime` int(11) NOT NULL DEFAULT '0' COMMENT '状态时间戳',
  `stateduration` int(11) NOT NULL DEFAULT '0' COMMENT '状态持续多少秒',
  `action` int(11) NOT NULL DEFAULT '0' COMMENT '行为',
  `from_type` smallint(6) NOT NULL DEFAULT '0' COMMENT '出发的对象类型',
  `from_id` int(11) NOT NULL DEFAULT '0' COMMENT '出发的对象ID',
  `from_index` int(11) NOT NULL DEFAULT '0' COMMENT '出发的对象索引',
  `from_posx` smallint(6) NOT NULL DEFAULT '0' COMMENT '出发的对象坐标',
  `from_posy` smallint(6) NOT NULL DEFAULT '0' COMMENT '出发的对象坐标',
  `to_type` smallint(6) NOT NULL DEFAULT '0' COMMENT '目的对象类型',
  `to_id` int(11) NOT NULL DEFAULT '0' COMMENT '目的对象ID',
  `to_index` int(11) NOT NULL DEFAULT '0' COMMENT '目的对象索引',
  `to_posx` smallint(6) NOT NULL DEFAULT '0' COMMENT '目的对象坐标',
  `to_posy` smallint(6) NOT NULL DEFAULT '0' COMMENT '目的对象坐标',
  `posx` smallint(6) NOT NULL DEFAULT '0' COMMENT '当前坐标',
  `posy` smallint(6) NOT NULL DEFAULT '0' COMMENT '当前坐标',
  `herokind0` smallint(6) NOT NULL DEFAULT '0' COMMENT '武将',
  `herokind1` smallint(6) NOT NULL DEFAULT '0' COMMENT '武将',
  `herokind2` smallint(6) NOT NULL DEFAULT '0' COMMENT '武将',
  `herokind3` smallint(6) NOT NULL DEFAULT '0' COMMENT '武将',
  PRIMARY KEY (`index`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
