g_kingwar_config = {
[1] = { id=1,exp=25000000,drawing_num=6,drawing_other=0,rank_award_point=5000,totalkill=10000,totalkill_award_point=1000,treasure_donum=0,treasure_costpoint=0,treasure_costtoken=0,treasure_award=0,treasure_equipodds=0,exchange_item=0,exchange_point=0,},
[2] = { id=2,exp=55000000,drawing_num=8,drawing_other=0,rank_award_point=4200,totalkill=20000,totalkill_award_point=2200,treasure_donum=0,treasure_costpoint=0,treasure_costtoken=0,treasure_award=0,treasure_equipodds=0,exchange_item=0,exchange_point=0,},
[3] = { id=3,exp=100000000,drawing_num=10,drawing_other=0,rank_award_point=3600,totalkill=0,totalkill_award_point=0,treasure_donum=0,treasure_costpoint=0,treasure_costtoken=0,treasure_award=0,treasure_equipodds=0,exchange_item=0,exchange_point=0,},
[4] = { id=4,exp=0,drawing_num=0,drawing_other=0,rank_award_point=3500,totalkill=0,totalkill_award_point=0,treasure_donum=0,treasure_costpoint=0,treasure_costtoken=0,treasure_award=0,treasure_equipodds=0,exchange_item=0,exchange_point=0,},
[5] = { id=5,exp=0,drawing_num=0,drawing_other=0,rank_award_point=3400,totalkill=0,totalkill_award_point=0,treasure_donum=0,treasure_costpoint=0,treasure_costtoken=0,treasure_award=0,treasure_equipodds=0,exchange_item=0,exchange_point=0,},
[6] = { id=6,exp=0,drawing_num=0,drawing_other=0,rank_award_point=3300,totalkill=0,totalkill_award_point=0,treasure_donum=0,treasure_costpoint=0,treasure_costtoken=0,treasure_award=0,treasure_equipodds=0,exchange_item=0,exchange_point=0,},
[7] = { id=7,exp=0,drawing_num=0,drawing_other=0,rank_award_point=3200,totalkill=0,totalkill_award_point=0,treasure_donum=0,treasure_costpoint=0,treasure_costtoken=0,treasure_award=0,treasure_equipodds=0,exchange_item=0,exchange_point=0,},
[8] = { id=8,exp=0,drawing_num=0,drawing_other=0,rank_award_point=3100,totalkill=0,totalkill_award_point=0,treasure_donum=0,treasure_costpoint=0,treasure_costtoken=0,treasure_award=0,treasure_equipodds=0,exchange_item=0,exchange_point=0,},
[9] = { id=9,exp=0,drawing_num=0,drawing_other=0,rank_award_point=3000,totalkill=0,totalkill_award_point=0,treasure_donum=0,treasure_costpoint=0,treasure_costtoken=0,treasure_award=0,treasure_equipodds=0,exchange_item=0,exchange_point=0,},
[10] = { id=10,exp=0,drawing_num=0,drawing_other=0,rank_award_point=2900,totalkill=0,totalkill_award_point=0,treasure_donum=0,treasure_costpoint=0,treasure_costtoken=0,treasure_award=0,treasure_equipodds=0,exchange_item=0,exchange_point=0,},
}
