//this source code was auto-generated by tolua#, do not modify it
using System;
using System.Collections.Generic;
using LuaInterface;

public static class DelegateFactory
{
	public delegate Delegate DelegateValue(LuaFunction func, LuaTable self, bool flag);
	public static Dictionary<Type, DelegateValue> dict = new Dictionary<Type, DelegateValue>();

	static DelegateFactory()
	{
		Register();
	}

	[NoToLuaAttribute]
	public static void Register()
	{
		dict.Clear();
		dict.Add(typeof(System.Action), System_Action);
		dict.Add(typeof(UnityEngine.Events.UnityAction), UnityEngine_Events_UnityAction);
		dict.Add(typeof(System.Predicate<int>), System_Predicate_int);
		dict.Add(typeof(System.Action<int>), System_Action_int);
		dict.Add(typeof(System.Comparison<int>), System_Comparison_int);
		dict.Add(typeof(UnityEngine.Camera.CameraCallback), UnityEngine_Camera_CameraCallback);
		dict.Add(typeof(UnityEngine.Application.LowMemoryCallback), UnityEngine_Application_LowMemoryCallback);
		dict.Add(typeof(UnityEngine.Application.AdvertisingIdentifierCallback), UnityEngine_Application_AdvertisingIdentifierCallback);
		dict.Add(typeof(UnityEngine.Application.LogCallback), UnityEngine_Application_LogCallback);
		dict.Add(typeof(UnityEngine.AudioClip.PCMReaderCallback), UnityEngine_AudioClip_PCMReaderCallback);
		dict.Add(typeof(UnityEngine.AudioClip.PCMSetPositionCallback), UnityEngine_AudioClip_PCMSetPositionCallback);
		dict.Add(typeof(UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene,UnityEngine.SceneManagement.LoadSceneMode>), UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_LoadSceneMode);
		dict.Add(typeof(UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene>), UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene);
		dict.Add(typeof(UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene,UnityEngine.SceneManagement.Scene>), UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_Scene);
		dict.Add(typeof(GameManager.LuaExecute), GameManager_LuaExecute);
		dict.Add(typeof(System.Action<UnityEngine.Object>), System_Action_UnityEngine_Object);
		dict.Add(typeof(AudioManager.SwitchChanged), AudioManager_SwitchChanged);
		dict.Add(typeof(UnityEngine.Canvas.WillRenderCanvases), UnityEngine_Canvas_WillRenderCanvases);
		dict.Add(typeof(UnityEngine.UI.InputField.OnValidateInput), UnityEngine_UI_InputField_OnValidateInput);
		dict.Add(typeof(UIInputFieldSubmit.OnValidateInput), UIInputFieldSubmit_OnValidateInput);
		dict.Add(typeof(UnityEngine.RectTransform.ReapplyDrivenProperties), UnityEngine_RectTransform_ReapplyDrivenProperties);
		dict.Add(typeof(UITween.OnFinish), UITween_OnFinish);
		dict.Add(typeof(UIProgress.LuaCallback), UIProgress_LuaCallback);
		dict.Add(typeof(TypeWriter.LuaExecute), TypeWriter_LuaExecute);
		dict.Add(typeof(YlyDelegateUtil.StringDelegate), YlyDelegateUtil_StringDelegate);
		dict.Add(typeof(DragonBones.ListenerDelegate<DragonBones.EventObject>), DragonBones_ListenerDelegate_DragonBones_EventObject);
		dict.Add(typeof(Character.OnEvent), Character_OnEvent);
		dict.Add(typeof(UniWebView.PageStartedDelegate), UniWebView_PageStartedDelegate);
		dict.Add(typeof(UniWebView.PageFinishedDelegate), UniWebView_PageFinishedDelegate);
		dict.Add(typeof(UniWebView.PageErrorReceivedDelegate), UniWebView_PageErrorReceivedDelegate);
		dict.Add(typeof(UniWebView.MessageReceivedDelegate), UniWebView_MessageReceivedDelegate);
		dict.Add(typeof(UniWebView.ShouldCloseDelegate), UniWebView_ShouldCloseDelegate);
		dict.Add(typeof(UniWebView.KeyCodeReceivedDelegate), UniWebView_KeyCodeReceivedDelegate);
		dict.Add(typeof(UniWebView.OreintationChangedDelegate), UniWebView_OreintationChangedDelegate);
		dict.Add(typeof(System.Action<UniWebViewNativeResultPayload>), System_Action_UniWebViewNativeResultPayload);
		dict.Add(typeof(System.Action<string>), System_Action_string);
	}

    [NoToLuaAttribute]
    public static Delegate CreateDelegate(Type t, LuaFunction func = null)
    {
        DelegateValue Create = null;

        if (!dict.TryGetValue(t, out Create))
        {
            throw new LuaException(string.Format("Delegate {0} not register", LuaMisc.GetTypeName(t)));            
        }

        if (func != null)
        {
            LuaState state = func.GetLuaState();
            LuaDelegate target = state.GetLuaDelegate(func);
            
            if (target != null)
            {
                return Delegate.CreateDelegate(t, target, target.method);
            }  
            else
            {
                Delegate d = Create(func, null, false);
                target = d.Target as LuaDelegate;
                state.AddLuaDelegate(target, func);
                return d;
            }       
        }

        return Create(func, null, false);        
    }

    [NoToLuaAttribute]
    public static Delegate CreateDelegate(Type t, LuaFunction func, LuaTable self)
    {
        DelegateValue Create = null;

        if (!dict.TryGetValue(t, out Create))
        {
            throw new LuaException(string.Format("Delegate {0} not register", LuaMisc.GetTypeName(t)));
        }

        if (func != null)
        {
            LuaState state = func.GetLuaState();
            LuaDelegate target = state.GetLuaDelegate(func, self);

            if (target != null)
            {
                return Delegate.CreateDelegate(t, target, target.method);
            }
            else
            {
                Delegate d = Create(func, self, true);
                target = d.Target as LuaDelegate;
                state.AddLuaDelegate(target, func, self);
                return d;
            }
        }

        return Create(func, self, true);
    }

    [NoToLuaAttribute]
    public static Delegate RemoveDelegate(Delegate obj, LuaFunction func)
    {
        LuaState state = func.GetLuaState();
        Delegate[] ds = obj.GetInvocationList();

        for (int i = 0; i < ds.Length; i++)
        {
            LuaDelegate ld = ds[i].Target as LuaDelegate;

            if (ld != null && ld.func == func)
            {
                obj = Delegate.Remove(obj, ds[i]);
                state.DelayDispose(ld.func);
                break;
            }
        }

        return obj;
    }

    [NoToLuaAttribute]
    public static Delegate RemoveDelegate(Delegate obj, Delegate dg)
    {
        LuaDelegate remove = dg.Target as LuaDelegate;

        if (remove == null)
        {
            obj = Delegate.Remove(obj, dg);
            return obj;
        }

        LuaState state = remove.func.GetLuaState();
        Delegate[] ds = obj.GetInvocationList();        

        for (int i = 0; i < ds.Length; i++)
        {
            LuaDelegate ld = ds[i].Target as LuaDelegate;

            if (ld != null && ld == remove)
            {
                obj = Delegate.Remove(obj, ds[i]);
                state.DelayDispose(ld.func);
                state.DelayDispose(ld.self);
                break;
            }
        }

        return obj;
    }

	class System_Action_Event : LuaDelegate
	{
		public System_Action_Event(LuaFunction func) : base(func) { }
		public System_Action_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call()
		{
			func.Call();
		}

		public void CallWithSelf()
		{
			func.BeginPCall();
			func.Push(self);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Action fn = delegate() { };
			return fn;
		}

		if(!flag)
		{
			System_Action_Event target = new System_Action_Event(func);
			System.Action d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Action_Event target = new System_Action_Event(func, self);
			System.Action d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class UnityEngine_Events_UnityAction_Event : LuaDelegate
	{
		public UnityEngine_Events_UnityAction_Event(LuaFunction func) : base(func) { }
		public UnityEngine_Events_UnityAction_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call()
		{
			func.Call();
		}

		public void CallWithSelf()
		{
			func.BeginPCall();
			func.Push(self);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_Events_UnityAction(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.Events.UnityAction fn = delegate() { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_Events_UnityAction_Event target = new UnityEngine_Events_UnityAction_Event(func);
			UnityEngine.Events.UnityAction d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_Events_UnityAction_Event target = new UnityEngine_Events_UnityAction_Event(func, self);
			UnityEngine.Events.UnityAction d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class System_Predicate_int_Event : LuaDelegate
	{
		public System_Predicate_int_Event(LuaFunction func) : base(func) { }
		public System_Predicate_int_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public bool Call(int param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			bool ret = func.CheckBoolean();
			func.EndPCall();
			return ret;
		}

		public bool CallWithSelf(int param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			bool ret = func.CheckBoolean();
			func.EndPCall();
			return ret;
		}
	}

	public static Delegate System_Predicate_int(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Predicate<int> fn = delegate(int param0) { return false; };
			return fn;
		}

		if(!flag)
		{
			System_Predicate_int_Event target = new System_Predicate_int_Event(func);
			System.Predicate<int> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Predicate_int_Event target = new System_Predicate_int_Event(func, self);
			System.Predicate<int> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class System_Action_int_Event : LuaDelegate
	{
		public System_Action_int_Event(LuaFunction func) : base(func) { }
		public System_Action_int_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(int param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(int param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_int(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Action<int> fn = delegate(int param0) { };
			return fn;
		}

		if(!flag)
		{
			System_Action_int_Event target = new System_Action_int_Event(func);
			System.Action<int> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Action_int_Event target = new System_Action_int_Event(func, self);
			System.Action<int> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class System_Comparison_int_Event : LuaDelegate
	{
		public System_Comparison_int_Event(LuaFunction func) : base(func) { }
		public System_Comparison_int_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public int Call(int param0, int param1)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			int ret = (int)func.CheckNumber();
			func.EndPCall();
			return ret;
		}

		public int CallWithSelf(int param0, int param1)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			int ret = (int)func.CheckNumber();
			func.EndPCall();
			return ret;
		}
	}

	public static Delegate System_Comparison_int(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Comparison<int> fn = delegate(int param0, int param1) { return 0; };
			return fn;
		}

		if(!flag)
		{
			System_Comparison_int_Event target = new System_Comparison_int_Event(func);
			System.Comparison<int> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Comparison_int_Event target = new System_Comparison_int_Event(func, self);
			System.Comparison<int> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class UnityEngine_Camera_CameraCallback_Event : LuaDelegate
	{
		public UnityEngine_Camera_CameraCallback_Event(LuaFunction func) : base(func) { }
		public UnityEngine_Camera_CameraCallback_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(UnityEngine.Camera param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(UnityEngine.Camera param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_Camera_CameraCallback(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.Camera.CameraCallback fn = delegate(UnityEngine.Camera param0) { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_Camera_CameraCallback_Event target = new UnityEngine_Camera_CameraCallback_Event(func);
			UnityEngine.Camera.CameraCallback d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_Camera_CameraCallback_Event target = new UnityEngine_Camera_CameraCallback_Event(func, self);
			UnityEngine.Camera.CameraCallback d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class UnityEngine_Application_LowMemoryCallback_Event : LuaDelegate
	{
		public UnityEngine_Application_LowMemoryCallback_Event(LuaFunction func) : base(func) { }
		public UnityEngine_Application_LowMemoryCallback_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call()
		{
			func.Call();
		}

		public void CallWithSelf()
		{
			func.BeginPCall();
			func.Push(self);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_Application_LowMemoryCallback(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.Application.LowMemoryCallback fn = delegate() { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_Application_LowMemoryCallback_Event target = new UnityEngine_Application_LowMemoryCallback_Event(func);
			UnityEngine.Application.LowMemoryCallback d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_Application_LowMemoryCallback_Event target = new UnityEngine_Application_LowMemoryCallback_Event(func, self);
			UnityEngine.Application.LowMemoryCallback d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class UnityEngine_Application_AdvertisingIdentifierCallback_Event : LuaDelegate
	{
		public UnityEngine_Application_AdvertisingIdentifierCallback_Event(LuaFunction func) : base(func) { }
		public UnityEngine_Application_AdvertisingIdentifierCallback_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(string param0, bool param1, string param2)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(string param0, bool param1, string param2)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_Application_AdvertisingIdentifierCallback(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.Application.AdvertisingIdentifierCallback fn = delegate(string param0, bool param1, string param2) { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_Application_AdvertisingIdentifierCallback_Event target = new UnityEngine_Application_AdvertisingIdentifierCallback_Event(func);
			UnityEngine.Application.AdvertisingIdentifierCallback d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_Application_AdvertisingIdentifierCallback_Event target = new UnityEngine_Application_AdvertisingIdentifierCallback_Event(func, self);
			UnityEngine.Application.AdvertisingIdentifierCallback d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class UnityEngine_Application_LogCallback_Event : LuaDelegate
	{
		public UnityEngine_Application_LogCallback_Event(LuaFunction func) : base(func) { }
		public UnityEngine_Application_LogCallback_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(string param0, string param1, UnityEngine.LogType param2)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(string param0, string param1, UnityEngine.LogType param2)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_Application_LogCallback(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.Application.LogCallback fn = delegate(string param0, string param1, UnityEngine.LogType param2) { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_Application_LogCallback_Event target = new UnityEngine_Application_LogCallback_Event(func);
			UnityEngine.Application.LogCallback d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_Application_LogCallback_Event target = new UnityEngine_Application_LogCallback_Event(func, self);
			UnityEngine.Application.LogCallback d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class UnityEngine_AudioClip_PCMReaderCallback_Event : LuaDelegate
	{
		public UnityEngine_AudioClip_PCMReaderCallback_Event(LuaFunction func) : base(func) { }
		public UnityEngine_AudioClip_PCMReaderCallback_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(float[] param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(float[] param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_AudioClip_PCMReaderCallback(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.AudioClip.PCMReaderCallback fn = delegate(float[] param0) { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_AudioClip_PCMReaderCallback_Event target = new UnityEngine_AudioClip_PCMReaderCallback_Event(func);
			UnityEngine.AudioClip.PCMReaderCallback d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_AudioClip_PCMReaderCallback_Event target = new UnityEngine_AudioClip_PCMReaderCallback_Event(func, self);
			UnityEngine.AudioClip.PCMReaderCallback d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class UnityEngine_AudioClip_PCMSetPositionCallback_Event : LuaDelegate
	{
		public UnityEngine_AudioClip_PCMSetPositionCallback_Event(LuaFunction func) : base(func) { }
		public UnityEngine_AudioClip_PCMSetPositionCallback_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(int param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(int param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_AudioClip_PCMSetPositionCallback(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.AudioClip.PCMSetPositionCallback fn = delegate(int param0) { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_AudioClip_PCMSetPositionCallback_Event target = new UnityEngine_AudioClip_PCMSetPositionCallback_Event(func);
			UnityEngine.AudioClip.PCMSetPositionCallback d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_AudioClip_PCMSetPositionCallback_Event target = new UnityEngine_AudioClip_PCMSetPositionCallback_Event(func, self);
			UnityEngine.AudioClip.PCMSetPositionCallback d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_LoadSceneMode_Event : LuaDelegate
	{
		public UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_LoadSceneMode_Event(LuaFunction func) : base(func) { }
		public UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_LoadSceneMode_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(UnityEngine.SceneManagement.Scene param0, UnityEngine.SceneManagement.LoadSceneMode param1)
		{
			func.BeginPCall();
			func.PushValue(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(UnityEngine.SceneManagement.Scene param0, UnityEngine.SceneManagement.LoadSceneMode param1)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushValue(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_LoadSceneMode(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene,UnityEngine.SceneManagement.LoadSceneMode> fn = delegate(UnityEngine.SceneManagement.Scene param0, UnityEngine.SceneManagement.LoadSceneMode param1) { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_LoadSceneMode_Event target = new UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_LoadSceneMode_Event(func);
			UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene,UnityEngine.SceneManagement.LoadSceneMode> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_LoadSceneMode_Event target = new UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_LoadSceneMode_Event(func, self);
			UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene,UnityEngine.SceneManagement.LoadSceneMode> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_Event : LuaDelegate
	{
		public UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_Event(LuaFunction func) : base(func) { }
		public UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(UnityEngine.SceneManagement.Scene param0)
		{
			func.BeginPCall();
			func.PushValue(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(UnityEngine.SceneManagement.Scene param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushValue(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene> fn = delegate(UnityEngine.SceneManagement.Scene param0) { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_Event target = new UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_Event(func);
			UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_Event target = new UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_Event(func, self);
			UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_Scene_Event : LuaDelegate
	{
		public UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_Scene_Event(LuaFunction func) : base(func) { }
		public UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_Scene_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(UnityEngine.SceneManagement.Scene param0, UnityEngine.SceneManagement.Scene param1)
		{
			func.BeginPCall();
			func.PushValue(param0);
			func.PushValue(param1);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(UnityEngine.SceneManagement.Scene param0, UnityEngine.SceneManagement.Scene param1)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushValue(param0);
			func.PushValue(param1);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_Scene(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene,UnityEngine.SceneManagement.Scene> fn = delegate(UnityEngine.SceneManagement.Scene param0, UnityEngine.SceneManagement.Scene param1) { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_Scene_Event target = new UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_Scene_Event(func);
			UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene,UnityEngine.SceneManagement.Scene> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_Scene_Event target = new UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_Scene_Event(func, self);
			UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene,UnityEngine.SceneManagement.Scene> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class GameManager_LuaExecute_Event : LuaDelegate
	{
		public GameManager_LuaExecute_Event(LuaFunction func) : base(func) { }
		public GameManager_LuaExecute_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(object param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(object param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate GameManager_LuaExecute(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			GameManager.LuaExecute fn = delegate(object param0) { };
			return fn;
		}

		if(!flag)
		{
			GameManager_LuaExecute_Event target = new GameManager_LuaExecute_Event(func);
			GameManager.LuaExecute d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			GameManager_LuaExecute_Event target = new GameManager_LuaExecute_Event(func, self);
			GameManager.LuaExecute d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class System_Action_UnityEngine_Object_Event : LuaDelegate
	{
		public System_Action_UnityEngine_Object_Event(LuaFunction func) : base(func) { }
		public System_Action_UnityEngine_Object_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(UnityEngine.Object param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(UnityEngine.Object param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_UnityEngine_Object(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Action<UnityEngine.Object> fn = delegate(UnityEngine.Object param0) { };
			return fn;
		}

		if(!flag)
		{
			System_Action_UnityEngine_Object_Event target = new System_Action_UnityEngine_Object_Event(func);
			System.Action<UnityEngine.Object> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Action_UnityEngine_Object_Event target = new System_Action_UnityEngine_Object_Event(func, self);
			System.Action<UnityEngine.Object> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class AudioManager_SwitchChanged_Event : LuaDelegate
	{
		public AudioManager_SwitchChanged_Event(LuaFunction func) : base(func) { }
		public AudioManager_SwitchChanged_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(AudioManager.AudioType param0, bool param1)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(AudioManager.AudioType param0, bool param1)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate AudioManager_SwitchChanged(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			AudioManager.SwitchChanged fn = delegate(AudioManager.AudioType param0, bool param1) { };
			return fn;
		}

		if(!flag)
		{
			AudioManager_SwitchChanged_Event target = new AudioManager_SwitchChanged_Event(func);
			AudioManager.SwitchChanged d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			AudioManager_SwitchChanged_Event target = new AudioManager_SwitchChanged_Event(func, self);
			AudioManager.SwitchChanged d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class UnityEngine_Canvas_WillRenderCanvases_Event : LuaDelegate
	{
		public UnityEngine_Canvas_WillRenderCanvases_Event(LuaFunction func) : base(func) { }
		public UnityEngine_Canvas_WillRenderCanvases_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call()
		{
			func.Call();
		}

		public void CallWithSelf()
		{
			func.BeginPCall();
			func.Push(self);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_Canvas_WillRenderCanvases(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.Canvas.WillRenderCanvases fn = delegate() { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_Canvas_WillRenderCanvases_Event target = new UnityEngine_Canvas_WillRenderCanvases_Event(func);
			UnityEngine.Canvas.WillRenderCanvases d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_Canvas_WillRenderCanvases_Event target = new UnityEngine_Canvas_WillRenderCanvases_Event(func, self);
			UnityEngine.Canvas.WillRenderCanvases d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class UnityEngine_UI_InputField_OnValidateInput_Event : LuaDelegate
	{
		public UnityEngine_UI_InputField_OnValidateInput_Event(LuaFunction func) : base(func) { }
		public UnityEngine_UI_InputField_OnValidateInput_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public char Call(string param0, int param1, char param2)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.PCall();
			char ret = (char)func.CheckNumber();
			func.EndPCall();
			return ret;
		}

		public char CallWithSelf(string param0, int param1, char param2)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.PCall();
			char ret = (char)func.CheckNumber();
			func.EndPCall();
			return ret;
		}
	}

	public static Delegate UnityEngine_UI_InputField_OnValidateInput(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.UI.InputField.OnValidateInput fn = delegate(string param0, int param1, char param2) { return '\0'; };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_UI_InputField_OnValidateInput_Event target = new UnityEngine_UI_InputField_OnValidateInput_Event(func);
			UnityEngine.UI.InputField.OnValidateInput d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_UI_InputField_OnValidateInput_Event target = new UnityEngine_UI_InputField_OnValidateInput_Event(func, self);
			UnityEngine.UI.InputField.OnValidateInput d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class UIInputFieldSubmit_OnValidateInput_Event : LuaDelegate
	{
		public UIInputFieldSubmit_OnValidateInput_Event(LuaFunction func) : base(func) { }
		public UIInputFieldSubmit_OnValidateInput_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public char Call(string param0, int param1, char param2)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.PCall();
			char ret = (char)func.CheckNumber();
			func.EndPCall();
			return ret;
		}

		public char CallWithSelf(string param0, int param1, char param2)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.PCall();
			char ret = (char)func.CheckNumber();
			func.EndPCall();
			return ret;
		}
	}

	public static Delegate UIInputFieldSubmit_OnValidateInput(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UIInputFieldSubmit.OnValidateInput fn = delegate(string param0, int param1, char param2) { return '\0'; };
			return fn;
		}

		if(!flag)
		{
			UIInputFieldSubmit_OnValidateInput_Event target = new UIInputFieldSubmit_OnValidateInput_Event(func);
			UIInputFieldSubmit.OnValidateInput d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UIInputFieldSubmit_OnValidateInput_Event target = new UIInputFieldSubmit_OnValidateInput_Event(func, self);
			UIInputFieldSubmit.OnValidateInput d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class UnityEngine_RectTransform_ReapplyDrivenProperties_Event : LuaDelegate
	{
		public UnityEngine_RectTransform_ReapplyDrivenProperties_Event(LuaFunction func) : base(func) { }
		public UnityEngine_RectTransform_ReapplyDrivenProperties_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(UnityEngine.RectTransform param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(UnityEngine.RectTransform param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_RectTransform_ReapplyDrivenProperties(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.RectTransform.ReapplyDrivenProperties fn = delegate(UnityEngine.RectTransform param0) { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_RectTransform_ReapplyDrivenProperties_Event target = new UnityEngine_RectTransform_ReapplyDrivenProperties_Event(func);
			UnityEngine.RectTransform.ReapplyDrivenProperties d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_RectTransform_ReapplyDrivenProperties_Event target = new UnityEngine_RectTransform_ReapplyDrivenProperties_Event(func, self);
			UnityEngine.RectTransform.ReapplyDrivenProperties d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class UITween_OnFinish_Event : LuaDelegate
	{
		public UITween_OnFinish_Event(LuaFunction func) : base(func) { }
		public UITween_OnFinish_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(UnityEngine.GameObject param0, int param1)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(UnityEngine.GameObject param0, int param1)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UITween_OnFinish(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UITween.OnFinish fn = delegate(UnityEngine.GameObject param0, int param1) { };
			return fn;
		}

		if(!flag)
		{
			UITween_OnFinish_Event target = new UITween_OnFinish_Event(func);
			UITween.OnFinish d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UITween_OnFinish_Event target = new UITween_OnFinish_Event(func, self);
			UITween.OnFinish d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class UIProgress_LuaCallback_Event : LuaDelegate
	{
		public UIProgress_LuaCallback_Event(LuaFunction func) : base(func) { }
		public UIProgress_LuaCallback_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(object param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(object param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UIProgress_LuaCallback(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UIProgress.LuaCallback fn = delegate(object param0) { };
			return fn;
		}

		if(!flag)
		{
			UIProgress_LuaCallback_Event target = new UIProgress_LuaCallback_Event(func);
			UIProgress.LuaCallback d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UIProgress_LuaCallback_Event target = new UIProgress_LuaCallback_Event(func, self);
			UIProgress.LuaCallback d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class TypeWriter_LuaExecute_Event : LuaDelegate
	{
		public TypeWriter_LuaExecute_Event(LuaFunction func) : base(func) { }
		public TypeWriter_LuaExecute_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call()
		{
			func.Call();
		}

		public void CallWithSelf()
		{
			func.BeginPCall();
			func.Push(self);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate TypeWriter_LuaExecute(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			TypeWriter.LuaExecute fn = delegate() { };
			return fn;
		}

		if(!flag)
		{
			TypeWriter_LuaExecute_Event target = new TypeWriter_LuaExecute_Event(func);
			TypeWriter.LuaExecute d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			TypeWriter_LuaExecute_Event target = new TypeWriter_LuaExecute_Event(func, self);
			TypeWriter.LuaExecute d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class YlyDelegateUtil_StringDelegate_Event : LuaDelegate
	{
		public YlyDelegateUtil_StringDelegate_Event(LuaFunction func) : base(func) { }
		public YlyDelegateUtil_StringDelegate_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(string param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(string param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate YlyDelegateUtil_StringDelegate(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			YlyDelegateUtil.StringDelegate fn = delegate(string param0) { };
			return fn;
		}

		if(!flag)
		{
			YlyDelegateUtil_StringDelegate_Event target = new YlyDelegateUtil_StringDelegate_Event(func);
			YlyDelegateUtil.StringDelegate d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			YlyDelegateUtil_StringDelegate_Event target = new YlyDelegateUtil_StringDelegate_Event(func, self);
			YlyDelegateUtil.StringDelegate d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class DragonBones_ListenerDelegate_DragonBones_EventObject_Event : LuaDelegate
	{
		public DragonBones_ListenerDelegate_DragonBones_EventObject_Event(LuaFunction func) : base(func) { }
		public DragonBones_ListenerDelegate_DragonBones_EventObject_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(string param0, DragonBones.EventObject param1)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PushObject(param1);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(string param0, DragonBones.EventObject param1)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PushObject(param1);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate DragonBones_ListenerDelegate_DragonBones_EventObject(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			DragonBones.ListenerDelegate<DragonBones.EventObject> fn = delegate(string param0, DragonBones.EventObject param1) { };
			return fn;
		}

		if(!flag)
		{
			DragonBones_ListenerDelegate_DragonBones_EventObject_Event target = new DragonBones_ListenerDelegate_DragonBones_EventObject_Event(func);
			DragonBones.ListenerDelegate<DragonBones.EventObject> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			DragonBones_ListenerDelegate_DragonBones_EventObject_Event target = new DragonBones_ListenerDelegate_DragonBones_EventObject_Event(func, self);
			DragonBones.ListenerDelegate<DragonBones.EventObject> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class Character_OnEvent_Event : LuaDelegate
	{
		public Character_OnEvent_Event(LuaFunction func) : base(func) { }
		public Character_OnEvent_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(Character param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(Character param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate Character_OnEvent(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			Character.OnEvent fn = delegate(Character param0) { };
			return fn;
		}

		if(!flag)
		{
			Character_OnEvent_Event target = new Character_OnEvent_Event(func);
			Character.OnEvent d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			Character_OnEvent_Event target = new Character_OnEvent_Event(func, self);
			Character.OnEvent d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class UniWebView_PageStartedDelegate_Event : LuaDelegate
	{
		public UniWebView_PageStartedDelegate_Event(LuaFunction func) : base(func) { }
		public UniWebView_PageStartedDelegate_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(UniWebView param0, string param1)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(UniWebView param0, string param1)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UniWebView_PageStartedDelegate(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UniWebView.PageStartedDelegate fn = delegate(UniWebView param0, string param1) { };
			return fn;
		}

		if(!flag)
		{
			UniWebView_PageStartedDelegate_Event target = new UniWebView_PageStartedDelegate_Event(func);
			UniWebView.PageStartedDelegate d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UniWebView_PageStartedDelegate_Event target = new UniWebView_PageStartedDelegate_Event(func, self);
			UniWebView.PageStartedDelegate d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class UniWebView_PageFinishedDelegate_Event : LuaDelegate
	{
		public UniWebView_PageFinishedDelegate_Event(LuaFunction func) : base(func) { }
		public UniWebView_PageFinishedDelegate_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(UniWebView param0, int param1, string param2)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(UniWebView param0, int param1, string param2)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UniWebView_PageFinishedDelegate(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UniWebView.PageFinishedDelegate fn = delegate(UniWebView param0, int param1, string param2) { };
			return fn;
		}

		if(!flag)
		{
			UniWebView_PageFinishedDelegate_Event target = new UniWebView_PageFinishedDelegate_Event(func);
			UniWebView.PageFinishedDelegate d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UniWebView_PageFinishedDelegate_Event target = new UniWebView_PageFinishedDelegate_Event(func, self);
			UniWebView.PageFinishedDelegate d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class UniWebView_PageErrorReceivedDelegate_Event : LuaDelegate
	{
		public UniWebView_PageErrorReceivedDelegate_Event(LuaFunction func) : base(func) { }
		public UniWebView_PageErrorReceivedDelegate_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(UniWebView param0, int param1, string param2)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(UniWebView param0, int param1, string param2)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UniWebView_PageErrorReceivedDelegate(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UniWebView.PageErrorReceivedDelegate fn = delegate(UniWebView param0, int param1, string param2) { };
			return fn;
		}

		if(!flag)
		{
			UniWebView_PageErrorReceivedDelegate_Event target = new UniWebView_PageErrorReceivedDelegate_Event(func);
			UniWebView.PageErrorReceivedDelegate d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UniWebView_PageErrorReceivedDelegate_Event target = new UniWebView_PageErrorReceivedDelegate_Event(func, self);
			UniWebView.PageErrorReceivedDelegate d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class UniWebView_MessageReceivedDelegate_Event : LuaDelegate
	{
		public UniWebView_MessageReceivedDelegate_Event(LuaFunction func) : base(func) { }
		public UniWebView_MessageReceivedDelegate_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(UniWebView param0, UniWebViewMessage param1)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PushValue(param1);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(UniWebView param0, UniWebViewMessage param1)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PushValue(param1);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UniWebView_MessageReceivedDelegate(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UniWebView.MessageReceivedDelegate fn = delegate(UniWebView param0, UniWebViewMessage param1) { };
			return fn;
		}

		if(!flag)
		{
			UniWebView_MessageReceivedDelegate_Event target = new UniWebView_MessageReceivedDelegate_Event(func);
			UniWebView.MessageReceivedDelegate d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UniWebView_MessageReceivedDelegate_Event target = new UniWebView_MessageReceivedDelegate_Event(func, self);
			UniWebView.MessageReceivedDelegate d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class UniWebView_ShouldCloseDelegate_Event : LuaDelegate
	{
		public UniWebView_ShouldCloseDelegate_Event(LuaFunction func) : base(func) { }
		public UniWebView_ShouldCloseDelegate_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public bool Call(UniWebView param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			bool ret = func.CheckBoolean();
			func.EndPCall();
			return ret;
		}

		public bool CallWithSelf(UniWebView param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			bool ret = func.CheckBoolean();
			func.EndPCall();
			return ret;
		}
	}

	public static Delegate UniWebView_ShouldCloseDelegate(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UniWebView.ShouldCloseDelegate fn = delegate(UniWebView param0) { return false; };
			return fn;
		}

		if(!flag)
		{
			UniWebView_ShouldCloseDelegate_Event target = new UniWebView_ShouldCloseDelegate_Event(func);
			UniWebView.ShouldCloseDelegate d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UniWebView_ShouldCloseDelegate_Event target = new UniWebView_ShouldCloseDelegate_Event(func, self);
			UniWebView.ShouldCloseDelegate d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class UniWebView_KeyCodeReceivedDelegate_Event : LuaDelegate
	{
		public UniWebView_KeyCodeReceivedDelegate_Event(LuaFunction func) : base(func) { }
		public UniWebView_KeyCodeReceivedDelegate_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(UniWebView param0, int param1)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(UniWebView param0, int param1)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UniWebView_KeyCodeReceivedDelegate(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UniWebView.KeyCodeReceivedDelegate fn = delegate(UniWebView param0, int param1) { };
			return fn;
		}

		if(!flag)
		{
			UniWebView_KeyCodeReceivedDelegate_Event target = new UniWebView_KeyCodeReceivedDelegate_Event(func);
			UniWebView.KeyCodeReceivedDelegate d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UniWebView_KeyCodeReceivedDelegate_Event target = new UniWebView_KeyCodeReceivedDelegate_Event(func, self);
			UniWebView.KeyCodeReceivedDelegate d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class UniWebView_OreintationChangedDelegate_Event : LuaDelegate
	{
		public UniWebView_OreintationChangedDelegate_Event(LuaFunction func) : base(func) { }
		public UniWebView_OreintationChangedDelegate_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(UniWebView param0, UnityEngine.ScreenOrientation param1)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(UniWebView param0, UnityEngine.ScreenOrientation param1)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UniWebView_OreintationChangedDelegate(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UniWebView.OreintationChangedDelegate fn = delegate(UniWebView param0, UnityEngine.ScreenOrientation param1) { };
			return fn;
		}

		if(!flag)
		{
			UniWebView_OreintationChangedDelegate_Event target = new UniWebView_OreintationChangedDelegate_Event(func);
			UniWebView.OreintationChangedDelegate d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UniWebView_OreintationChangedDelegate_Event target = new UniWebView_OreintationChangedDelegate_Event(func, self);
			UniWebView.OreintationChangedDelegate d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class System_Action_UniWebViewNativeResultPayload_Event : LuaDelegate
	{
		public System_Action_UniWebViewNativeResultPayload_Event(LuaFunction func) : base(func) { }
		public System_Action_UniWebViewNativeResultPayload_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(UniWebViewNativeResultPayload param0)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(UniWebViewNativeResultPayload param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_UniWebViewNativeResultPayload(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Action<UniWebViewNativeResultPayload> fn = delegate(UniWebViewNativeResultPayload param0) { };
			return fn;
		}

		if(!flag)
		{
			System_Action_UniWebViewNativeResultPayload_Event target = new System_Action_UniWebViewNativeResultPayload_Event(func);
			System.Action<UniWebViewNativeResultPayload> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Action_UniWebViewNativeResultPayload_Event target = new System_Action_UniWebViewNativeResultPayload_Event(func, self);
			System.Action<UniWebViewNativeResultPayload> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	class System_Action_string_Event : LuaDelegate
	{
		public System_Action_string_Event(LuaFunction func) : base(func) { }
		public System_Action_string_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(string param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(string param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_string(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Action<string> fn = delegate(string param0) { };
			return fn;
		}

		if(!flag)
		{
			System_Action_string_Event target = new System_Action_string_Event(func);
			System.Action<string> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Action_string_Event target = new System_Action_string_Event(func, self);
			System.Action<string> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

}

