//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UniWebViewTransitionEdgeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UniWebViewTransitionEdge));
		L.RegVar("None", get_None, null);
		L.RegVar("Top", get_Top, null);
		L.RegVar("Left", get_Left, null);
		L.RegVar("Bottom", get_Bottom, null);
		L.RegVar("Right", get_Right, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_None(IntPtr L)
	{
		ToLua.Push(L, UniWebViewTransitionEdge.None);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Top(IntPtr L)
	{
		ToLua.Push(L, UniWebViewTransitionEdge.Top);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Left(IntPtr L)
	{
		ToLua.Push(L, UniWebViewTransitionEdge.Left);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Bottom(IntPtr L)
	{
		ToLua.Push(L, UniWebViewTransitionEdge.Bottom);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Right(IntPtr L)
	{
		ToLua.Push(L, UniWebViewTransitionEdge.Right);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UniWebViewTransitionEdge o = (UniWebViewTransitionEdge)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

