//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UniWebViewWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UniWebView), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("UpdateFrame", UpdateFrame);
		L.RegFunction("Load", Load);
		L.RegFunction("LoadHTMLString", LoadHTMLString);
		L.RegFunction("Reload", Reload);
		L.RegFunction("Stop", Stop);
		L.RegFunction("GoBack", GoBack);
		L.RegFunction("GoForward", GoForward);
		L.RegFunction("SetOpenLinksInExternalBrowser", SetOpenLinksInExternalBrowser);
		L.RegFunction("Show", Show);
		L.RegFunction("Hide", Hide);
		L.RegFunction("AnimateTo", AnimateTo);
		L.RegFunction("AddJavaScript", AddJavaScript);
		L.RegFunction("EvaluateJavaScript", EvaluateJavaScript);
		L.RegFunction("AddUrlScheme", AddUrlScheme);
		L.RegFunction("RemoveUrlScheme", RemoveUrlScheme);
		L.RegFunction("AddSslExceptionDomain", AddSslExceptionDomain);
		L.RegFunction("RemoveSslExceptionDomain", RemoveSslExceptionDomain);
		L.RegFunction("SetHeaderField", SetHeaderField);
		L.RegFunction("SetUserAgent", SetUserAgent);
		L.RegFunction("GetUserAgent", GetUserAgent);
		L.RegFunction("SetAllowAutoPlay", SetAllowAutoPlay);
		L.RegFunction("SetAllowInlinePlay", SetAllowInlinePlay);
		L.RegFunction("SetJavaScriptEnabled", SetJavaScriptEnabled);
		L.RegFunction("SetAllowJavaScriptOpenWindow", SetAllowJavaScriptOpenWindow);
		L.RegFunction("CleanCache", CleanCache);
		L.RegFunction("ClearCookies", ClearCookies);
		L.RegFunction("SetCookie", SetCookie);
		L.RegFunction("GetCookie", GetCookie);
		L.RegFunction("ClearHttpAuthUsernamePassword", ClearHttpAuthUsernamePassword);
		L.RegFunction("SetShowSpinnerWhileLoading", SetShowSpinnerWhileLoading);
		L.RegFunction("SetSpinnerText", SetSpinnerText);
		L.RegFunction("SetHorizontalScrollBarEnabled", SetHorizontalScrollBarEnabled);
		L.RegFunction("SetVerticalScrollBarEnabled", SetVerticalScrollBarEnabled);
		L.RegFunction("SetBouncesEnabled", SetBouncesEnabled);
		L.RegFunction("SetZoomEnabled", SetZoomEnabled);
		L.RegFunction("AddPermissionTrustDomain", AddPermissionTrustDomain);
		L.RegFunction("RemovePermissionTrustDomain", RemovePermissionTrustDomain);
		L.RegFunction("SetBackButtonEnabled", SetBackButtonEnabled);
		L.RegFunction("SetUseWideViewPort", SetUseWideViewPort);
		L.RegFunction("SetLoadWithOverviewMode", SetLoadWithOverviewMode);
		L.RegFunction("SetImmersiveModeEnabled", SetImmersiveModeEnabled);
		L.RegFunction("SetShowToolbar", SetShowToolbar);
		L.RegFunction("SetToolbarDoneButtonText", SetToolbarDoneButtonText);
		L.RegFunction("SetWebContentsDebuggingEnabled", SetWebContentsDebuggingEnabled);
		L.RegFunction("SetWindowUserResizeEnabled", SetWindowUserResizeEnabled);
		L.RegFunction("GetHTMLContent", GetHTMLContent);
		L.RegFunction("Print", Print);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Frame", get_Frame, set_Frame);
		L.RegVar("ReferenceRectTransform", get_ReferenceRectTransform, set_ReferenceRectTransform);
		L.RegVar("Url", get_Url, null);
		L.RegVar("CanGoBack", get_CanGoBack, null);
		L.RegVar("CanGoForward", get_CanGoForward, null);
		L.RegVar("BackgroundColor", get_BackgroundColor, set_BackgroundColor);
		L.RegVar("Alpha", get_Alpha, set_Alpha);
		L.RegVar("OnPageStarted", get_OnPageStarted, set_OnPageStarted);
		L.RegVar("OnPageFinished", get_OnPageFinished, set_OnPageFinished);
		L.RegVar("OnPageErrorReceived", get_OnPageErrorReceived, set_OnPageErrorReceived);
		L.RegVar("OnMessageReceived", get_OnMessageReceived, set_OnMessageReceived);
		L.RegVar("OnShouldClose", get_OnShouldClose, set_OnShouldClose);
		L.RegVar("OnKeyCodeReceived", get_OnKeyCodeReceived, set_OnKeyCodeReceived);
		L.RegVar("OnOreintationChanged", get_OnOreintationChanged, set_OnOreintationChanged);
		L.RegFunction("OreintationChangedDelegate", UniWebView_OreintationChangedDelegate);
		L.RegFunction("KeyCodeReceivedDelegate", UniWebView_KeyCodeReceivedDelegate);
		L.RegFunction("ShouldCloseDelegate", UniWebView_ShouldCloseDelegate);
		L.RegFunction("MessageReceivedDelegate", UniWebView_MessageReceivedDelegate);
		L.RegFunction("PageErrorReceivedDelegate", UniWebView_PageErrorReceivedDelegate);
		L.RegFunction("PageFinishedDelegate", UniWebView_PageFinishedDelegate);
		L.RegFunction("PageStartedDelegate", UniWebView_PageStartedDelegate);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UpdateFrame(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UniWebView obj = (UniWebView)ToLua.CheckObject(L, 1, typeof(UniWebView));
			obj.UpdateFrame();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Load(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			UniWebView obj = (UniWebView)ToLua.CheckObject(L, 1, typeof(UniWebView));
			string arg0 = ToLua.CheckString(L, 2);
			bool arg1 = LuaDLL.luaL_checkboolean(L, 3);
			obj.Load(arg0, arg1);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadHTMLString(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			UniWebView obj = (UniWebView)ToLua.CheckObject(L, 1, typeof(UniWebView));
			string arg0 = ToLua.CheckString(L, 2);
			string arg1 = ToLua.CheckString(L, 3);
			bool arg2 = LuaDLL.luaL_checkboolean(L, 4);
			obj.LoadHTMLString(arg0, arg1, arg2);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Reload(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UniWebView obj = (UniWebView)ToLua.CheckObject(L, 1, typeof(UniWebView));
			obj.Reload();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Stop(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UniWebView obj = (UniWebView)ToLua.CheckObject(L, 1, typeof(UniWebView));
			obj.Stop();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GoBack(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UniWebView obj = (UniWebView)ToLua.CheckObject(L, 1, typeof(UniWebView));
			obj.GoBack();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GoForward(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UniWebView obj = (UniWebView)ToLua.CheckObject(L, 1, typeof(UniWebView));
			obj.GoForward();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetOpenLinksInExternalBrowser(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UniWebView obj = (UniWebView)ToLua.CheckObject(L, 1, typeof(UniWebView));
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.SetOpenLinksInExternalBrowser(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Show(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 5);
			UniWebView obj = (UniWebView)ToLua.CheckObject(L, 1, typeof(UniWebView));
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			UniWebViewTransitionEdge arg1 = (UniWebViewTransitionEdge)ToLua.CheckObject(L, 3, typeof(UniWebViewTransitionEdge));
			float arg2 = (float)LuaDLL.luaL_checknumber(L, 4);
			System.Action arg3 = null;
			LuaTypes funcType5 = LuaDLL.lua_type(L, 5);

			if (funcType5 != LuaTypes.LUA_TFUNCTION)
			{
				 arg3 = (System.Action)ToLua.CheckObject(L, 5, typeof(System.Action));
			}
			else
			{
				LuaFunction func = ToLua.ToLuaFunction(L, 5);
				arg3 = DelegateFactory.CreateDelegate(typeof(System.Action), func) as System.Action;
			}

			bool o = obj.Show(arg0, arg1, arg2, arg3);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Hide(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 5);
			UniWebView obj = (UniWebView)ToLua.CheckObject(L, 1, typeof(UniWebView));
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			UniWebViewTransitionEdge arg1 = (UniWebViewTransitionEdge)ToLua.CheckObject(L, 3, typeof(UniWebViewTransitionEdge));
			float arg2 = (float)LuaDLL.luaL_checknumber(L, 4);
			System.Action arg3 = null;
			LuaTypes funcType5 = LuaDLL.lua_type(L, 5);

			if (funcType5 != LuaTypes.LUA_TFUNCTION)
			{
				 arg3 = (System.Action)ToLua.CheckObject(L, 5, typeof(System.Action));
			}
			else
			{
				LuaFunction func = ToLua.ToLuaFunction(L, 5);
				arg3 = DelegateFactory.CreateDelegate(typeof(System.Action), func) as System.Action;
			}

			bool o = obj.Hide(arg0, arg1, arg2, arg3);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AnimateTo(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 5);
			UniWebView obj = (UniWebView)ToLua.CheckObject(L, 1, typeof(UniWebView));
			UnityEngine.Rect arg0 = (UnityEngine.Rect)ToLua.CheckObject(L, 2, typeof(UnityEngine.Rect));
			float arg1 = (float)LuaDLL.luaL_checknumber(L, 3);
			float arg2 = (float)LuaDLL.luaL_checknumber(L, 4);
			System.Action arg3 = null;
			LuaTypes funcType5 = LuaDLL.lua_type(L, 5);

			if (funcType5 != LuaTypes.LUA_TFUNCTION)
			{
				 arg3 = (System.Action)ToLua.CheckObject(L, 5, typeof(System.Action));
			}
			else
			{
				LuaFunction func = ToLua.ToLuaFunction(L, 5);
				arg3 = DelegateFactory.CreateDelegate(typeof(System.Action), func) as System.Action;
			}

			bool o = obj.AnimateTo(arg0, arg1, arg2, arg3);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddJavaScript(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			UniWebView obj = (UniWebView)ToLua.CheckObject(L, 1, typeof(UniWebView));
			string arg0 = ToLua.CheckString(L, 2);
			System.Action<UniWebViewNativeResultPayload> arg1 = null;
			LuaTypes funcType3 = LuaDLL.lua_type(L, 3);

			if (funcType3 != LuaTypes.LUA_TFUNCTION)
			{
				 arg1 = (System.Action<UniWebViewNativeResultPayload>)ToLua.CheckObject(L, 3, typeof(System.Action<UniWebViewNativeResultPayload>));
			}
			else
			{
				LuaFunction func = ToLua.ToLuaFunction(L, 3);
				arg1 = DelegateFactory.CreateDelegate(typeof(System.Action<UniWebViewNativeResultPayload>), func) as System.Action<UniWebViewNativeResultPayload>;
			}

			obj.AddJavaScript(arg0, arg1);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int EvaluateJavaScript(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			UniWebView obj = (UniWebView)ToLua.CheckObject(L, 1, typeof(UniWebView));
			string arg0 = ToLua.CheckString(L, 2);
			System.Action<UniWebViewNativeResultPayload> arg1 = null;
			LuaTypes funcType3 = LuaDLL.lua_type(L, 3);

			if (funcType3 != LuaTypes.LUA_TFUNCTION)
			{
				 arg1 = (System.Action<UniWebViewNativeResultPayload>)ToLua.CheckObject(L, 3, typeof(System.Action<UniWebViewNativeResultPayload>));
			}
			else
			{
				LuaFunction func = ToLua.ToLuaFunction(L, 3);
				arg1 = DelegateFactory.CreateDelegate(typeof(System.Action<UniWebViewNativeResultPayload>), func) as System.Action<UniWebViewNativeResultPayload>;
			}

			obj.EvaluateJavaScript(arg0, arg1);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddUrlScheme(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UniWebView obj = (UniWebView)ToLua.CheckObject(L, 1, typeof(UniWebView));
			string arg0 = ToLua.CheckString(L, 2);
			obj.AddUrlScheme(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RemoveUrlScheme(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UniWebView obj = (UniWebView)ToLua.CheckObject(L, 1, typeof(UniWebView));
			string arg0 = ToLua.CheckString(L, 2);
			obj.RemoveUrlScheme(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddSslExceptionDomain(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UniWebView obj = (UniWebView)ToLua.CheckObject(L, 1, typeof(UniWebView));
			string arg0 = ToLua.CheckString(L, 2);
			obj.AddSslExceptionDomain(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RemoveSslExceptionDomain(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UniWebView obj = (UniWebView)ToLua.CheckObject(L, 1, typeof(UniWebView));
			string arg0 = ToLua.CheckString(L, 2);
			obj.RemoveSslExceptionDomain(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetHeaderField(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			UniWebView obj = (UniWebView)ToLua.CheckObject(L, 1, typeof(UniWebView));
			string arg0 = ToLua.CheckString(L, 2);
			string arg1 = ToLua.CheckString(L, 3);
			obj.SetHeaderField(arg0, arg1);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetUserAgent(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UniWebView obj = (UniWebView)ToLua.CheckObject(L, 1, typeof(UniWebView));
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetUserAgent(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetUserAgent(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UniWebView obj = (UniWebView)ToLua.CheckObject(L, 1, typeof(UniWebView));
			string o = obj.GetUserAgent();
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetAllowAutoPlay(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			bool arg0 = LuaDLL.luaL_checkboolean(L, 1);
			UniWebView.SetAllowAutoPlay(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetAllowInlinePlay(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			bool arg0 = LuaDLL.luaL_checkboolean(L, 1);
			UniWebView.SetAllowInlinePlay(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetJavaScriptEnabled(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			bool arg0 = LuaDLL.luaL_checkboolean(L, 1);
			UniWebView.SetJavaScriptEnabled(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetAllowJavaScriptOpenWindow(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			bool arg0 = LuaDLL.luaL_checkboolean(L, 1);
			UniWebView.SetAllowJavaScriptOpenWindow(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CleanCache(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UniWebView obj = (UniWebView)ToLua.CheckObject(L, 1, typeof(UniWebView));
			obj.CleanCache();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ClearCookies(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			UniWebView.ClearCookies();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetCookie(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			string arg0 = ToLua.CheckString(L, 1);
			string arg1 = ToLua.CheckString(L, 2);
			bool arg2 = LuaDLL.luaL_checkboolean(L, 3);
			UniWebView.SetCookie(arg0, arg1, arg2);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetCookie(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			string arg0 = ToLua.CheckString(L, 1);
			string arg1 = ToLua.CheckString(L, 2);
			bool arg2 = LuaDLL.luaL_checkboolean(L, 3);
			string o = UniWebView.GetCookie(arg0, arg1, arg2);
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ClearHttpAuthUsernamePassword(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			string arg0 = ToLua.CheckString(L, 1);
			string arg1 = ToLua.CheckString(L, 2);
			UniWebView.ClearHttpAuthUsernamePassword(arg0, arg1);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetShowSpinnerWhileLoading(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UniWebView obj = (UniWebView)ToLua.CheckObject(L, 1, typeof(UniWebView));
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.SetShowSpinnerWhileLoading(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetSpinnerText(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UniWebView obj = (UniWebView)ToLua.CheckObject(L, 1, typeof(UniWebView));
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetSpinnerText(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetHorizontalScrollBarEnabled(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UniWebView obj = (UniWebView)ToLua.CheckObject(L, 1, typeof(UniWebView));
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.SetHorizontalScrollBarEnabled(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetVerticalScrollBarEnabled(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UniWebView obj = (UniWebView)ToLua.CheckObject(L, 1, typeof(UniWebView));
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.SetVerticalScrollBarEnabled(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetBouncesEnabled(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UniWebView obj = (UniWebView)ToLua.CheckObject(L, 1, typeof(UniWebView));
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.SetBouncesEnabled(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetZoomEnabled(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UniWebView obj = (UniWebView)ToLua.CheckObject(L, 1, typeof(UniWebView));
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.SetZoomEnabled(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddPermissionTrustDomain(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UniWebView obj = (UniWebView)ToLua.CheckObject(L, 1, typeof(UniWebView));
			string arg0 = ToLua.CheckString(L, 2);
			obj.AddPermissionTrustDomain(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RemovePermissionTrustDomain(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UniWebView obj = (UniWebView)ToLua.CheckObject(L, 1, typeof(UniWebView));
			string arg0 = ToLua.CheckString(L, 2);
			obj.RemovePermissionTrustDomain(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetBackButtonEnabled(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UniWebView obj = (UniWebView)ToLua.CheckObject(L, 1, typeof(UniWebView));
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.SetBackButtonEnabled(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetUseWideViewPort(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UniWebView obj = (UniWebView)ToLua.CheckObject(L, 1, typeof(UniWebView));
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.SetUseWideViewPort(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetLoadWithOverviewMode(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UniWebView obj = (UniWebView)ToLua.CheckObject(L, 1, typeof(UniWebView));
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.SetLoadWithOverviewMode(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetImmersiveModeEnabled(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UniWebView obj = (UniWebView)ToLua.CheckObject(L, 1, typeof(UniWebView));
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.SetImmersiveModeEnabled(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetShowToolbar(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 5);
			UniWebView obj = (UniWebView)ToLua.CheckObject(L, 1, typeof(UniWebView));
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			bool arg1 = LuaDLL.luaL_checkboolean(L, 3);
			bool arg2 = LuaDLL.luaL_checkboolean(L, 4);
			bool arg3 = LuaDLL.luaL_checkboolean(L, 5);
			obj.SetShowToolbar(arg0, arg1, arg2, arg3);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetToolbarDoneButtonText(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UniWebView obj = (UniWebView)ToLua.CheckObject(L, 1, typeof(UniWebView));
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetToolbarDoneButtonText(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetWebContentsDebuggingEnabled(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			bool arg0 = LuaDLL.luaL_checkboolean(L, 1);
			UniWebView.SetWebContentsDebuggingEnabled(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetWindowUserResizeEnabled(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UniWebView obj = (UniWebView)ToLua.CheckObject(L, 1, typeof(UniWebView));
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.SetWindowUserResizeEnabled(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetHTMLContent(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UniWebView obj = (UniWebView)ToLua.CheckObject(L, 1, typeof(UniWebView));
			System.Action<string> arg0 = null;
			LuaTypes funcType2 = LuaDLL.lua_type(L, 2);

			if (funcType2 != LuaTypes.LUA_TFUNCTION)
			{
				 arg0 = (System.Action<string>)ToLua.CheckObject(L, 2, typeof(System.Action<string>));
			}
			else
			{
				LuaFunction func = ToLua.ToLuaFunction(L, 2);
				arg0 = DelegateFactory.CreateDelegate(typeof(System.Action<string>), func) as System.Action<string>;
			}

			obj.GetHTMLContent(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Print(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UniWebView obj = (UniWebView)ToLua.CheckObject(L, 1, typeof(UniWebView));
			obj.Print();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Frame(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UniWebView obj = (UniWebView)o;
			UnityEngine.Rect ret = obj.Frame;
			ToLua.PushValue(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index Frame on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ReferenceRectTransform(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UniWebView obj = (UniWebView)o;
			UnityEngine.RectTransform ret = obj.ReferenceRectTransform;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index ReferenceRectTransform on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Url(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UniWebView obj = (UniWebView)o;
			string ret = obj.Url;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index Url on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CanGoBack(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UniWebView obj = (UniWebView)o;
			bool ret = obj.CanGoBack;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index CanGoBack on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CanGoForward(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UniWebView obj = (UniWebView)o;
			bool ret = obj.CanGoForward;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index CanGoForward on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BackgroundColor(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UniWebView obj = (UniWebView)o;
			UnityEngine.Color ret = obj.BackgroundColor;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index BackgroundColor on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Alpha(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UniWebView obj = (UniWebView)o;
			float ret = obj.Alpha;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index Alpha on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnPageStarted(IntPtr L)
	{
		ToLua.Push(L, new EventObject("UniWebView.OnPageStarted"));
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnPageFinished(IntPtr L)
	{
		ToLua.Push(L, new EventObject("UniWebView.OnPageFinished"));
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnPageErrorReceived(IntPtr L)
	{
		ToLua.Push(L, new EventObject("UniWebView.OnPageErrorReceived"));
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnMessageReceived(IntPtr L)
	{
		ToLua.Push(L, new EventObject("UniWebView.OnMessageReceived"));
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnShouldClose(IntPtr L)
	{
		ToLua.Push(L, new EventObject("UniWebView.OnShouldClose"));
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnKeyCodeReceived(IntPtr L)
	{
		ToLua.Push(L, new EventObject("UniWebView.OnKeyCodeReceived"));
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnOreintationChanged(IntPtr L)
	{
		ToLua.Push(L, new EventObject("UniWebView.OnOreintationChanged"));
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Frame(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UniWebView obj = (UniWebView)o;
			UnityEngine.Rect arg0 = (UnityEngine.Rect)ToLua.CheckObject(L, 2, typeof(UnityEngine.Rect));
			obj.Frame = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index Frame on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_ReferenceRectTransform(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UniWebView obj = (UniWebView)o;
			UnityEngine.RectTransform arg0 = (UnityEngine.RectTransform)ToLua.CheckUnityObject(L, 2, typeof(UnityEngine.RectTransform));
			obj.ReferenceRectTransform = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index ReferenceRectTransform on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_BackgroundColor(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UniWebView obj = (UniWebView)o;
			UnityEngine.Color arg0 = ToLua.ToColor(L, 2);
			obj.BackgroundColor = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index BackgroundColor on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Alpha(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UniWebView obj = (UniWebView)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.Alpha = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index Alpha on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OnPageStarted(IntPtr L)
	{
		try
		{
			UniWebView obj = (UniWebView)ToLua.CheckObject(L, 1, typeof(UniWebView));
			EventObject arg0 = null;

			if (LuaDLL.lua_isuserdata(L, 2) != 0)
			{
				arg0 = (EventObject)ToLua.ToObject(L, 2);
			}
			else
			{
				return LuaDLL.luaL_throw(L, "The event 'UniWebView.OnPageStarted' can only appear on the left hand side of += or -= when used outside of the type 'UniWebView'");
			}

			if (arg0.op == EventOp.Add)
			{
				UniWebView.PageStartedDelegate ev = (UniWebView.PageStartedDelegate)DelegateFactory.CreateDelegate(typeof(UniWebView.PageStartedDelegate), arg0.func);
				obj.OnPageStarted += ev;
			}
			else if (arg0.op == EventOp.Sub)
			{
				UniWebView.PageStartedDelegate ev = (UniWebView.PageStartedDelegate)LuaMisc.GetEventHandler(obj, typeof(UniWebView), "OnPageStarted");
				Delegate[] ds = ev.GetInvocationList();
				LuaState state = LuaState.Get(L);

				for (int i = 0; i < ds.Length; i++)
				{
					ev = (UniWebView.PageStartedDelegate)ds[i];
					LuaDelegate ld = ev.Target as LuaDelegate;

					if (ld != null && ld.func == arg0.func)
					{
						obj.OnPageStarted -= ev;
						state.DelayDispose(ld.func);
						break;
					}
				}

				arg0.func.Dispose();
			}

			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OnPageFinished(IntPtr L)
	{
		try
		{
			UniWebView obj = (UniWebView)ToLua.CheckObject(L, 1, typeof(UniWebView));
			EventObject arg0 = null;

			if (LuaDLL.lua_isuserdata(L, 2) != 0)
			{
				arg0 = (EventObject)ToLua.ToObject(L, 2);
			}
			else
			{
				return LuaDLL.luaL_throw(L, "The event 'UniWebView.OnPageFinished' can only appear on the left hand side of += or -= when used outside of the type 'UniWebView'");
			}

			if (arg0.op == EventOp.Add)
			{
				UniWebView.PageFinishedDelegate ev = (UniWebView.PageFinishedDelegate)DelegateFactory.CreateDelegate(typeof(UniWebView.PageFinishedDelegate), arg0.func);
				obj.OnPageFinished += ev;
			}
			else if (arg0.op == EventOp.Sub)
			{
				UniWebView.PageFinishedDelegate ev = (UniWebView.PageFinishedDelegate)LuaMisc.GetEventHandler(obj, typeof(UniWebView), "OnPageFinished");
				Delegate[] ds = ev.GetInvocationList();
				LuaState state = LuaState.Get(L);

				for (int i = 0; i < ds.Length; i++)
				{
					ev = (UniWebView.PageFinishedDelegate)ds[i];
					LuaDelegate ld = ev.Target as LuaDelegate;

					if (ld != null && ld.func == arg0.func)
					{
						obj.OnPageFinished -= ev;
						state.DelayDispose(ld.func);
						break;
					}
				}

				arg0.func.Dispose();
			}

			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OnPageErrorReceived(IntPtr L)
	{
		try
		{
			UniWebView obj = (UniWebView)ToLua.CheckObject(L, 1, typeof(UniWebView));
			EventObject arg0 = null;

			if (LuaDLL.lua_isuserdata(L, 2) != 0)
			{
				arg0 = (EventObject)ToLua.ToObject(L, 2);
			}
			else
			{
				return LuaDLL.luaL_throw(L, "The event 'UniWebView.OnPageErrorReceived' can only appear on the left hand side of += or -= when used outside of the type 'UniWebView'");
			}

			if (arg0.op == EventOp.Add)
			{
				UniWebView.PageErrorReceivedDelegate ev = (UniWebView.PageErrorReceivedDelegate)DelegateFactory.CreateDelegate(typeof(UniWebView.PageErrorReceivedDelegate), arg0.func);
				obj.OnPageErrorReceived += ev;
			}
			else if (arg0.op == EventOp.Sub)
			{
				UniWebView.PageErrorReceivedDelegate ev = (UniWebView.PageErrorReceivedDelegate)LuaMisc.GetEventHandler(obj, typeof(UniWebView), "OnPageErrorReceived");
				Delegate[] ds = ev.GetInvocationList();
				LuaState state = LuaState.Get(L);

				for (int i = 0; i < ds.Length; i++)
				{
					ev = (UniWebView.PageErrorReceivedDelegate)ds[i];
					LuaDelegate ld = ev.Target as LuaDelegate;

					if (ld != null && ld.func == arg0.func)
					{
						obj.OnPageErrorReceived -= ev;
						state.DelayDispose(ld.func);
						break;
					}
				}

				arg0.func.Dispose();
			}

			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OnMessageReceived(IntPtr L)
	{
		try
		{
			UniWebView obj = (UniWebView)ToLua.CheckObject(L, 1, typeof(UniWebView));
			EventObject arg0 = null;

			if (LuaDLL.lua_isuserdata(L, 2) != 0)
			{
				arg0 = (EventObject)ToLua.ToObject(L, 2);
			}
			else
			{
				return LuaDLL.luaL_throw(L, "The event 'UniWebView.OnMessageReceived' can only appear on the left hand side of += or -= when used outside of the type 'UniWebView'");
			}

			if (arg0.op == EventOp.Add)
			{
				UniWebView.MessageReceivedDelegate ev = (UniWebView.MessageReceivedDelegate)DelegateFactory.CreateDelegate(typeof(UniWebView.MessageReceivedDelegate), arg0.func);
				obj.OnMessageReceived += ev;
			}
			else if (arg0.op == EventOp.Sub)
			{
				UniWebView.MessageReceivedDelegate ev = (UniWebView.MessageReceivedDelegate)LuaMisc.GetEventHandler(obj, typeof(UniWebView), "OnMessageReceived");
				Delegate[] ds = ev.GetInvocationList();
				LuaState state = LuaState.Get(L);

				for (int i = 0; i < ds.Length; i++)
				{
					ev = (UniWebView.MessageReceivedDelegate)ds[i];
					LuaDelegate ld = ev.Target as LuaDelegate;

					if (ld != null && ld.func == arg0.func)
					{
						obj.OnMessageReceived -= ev;
						state.DelayDispose(ld.func);
						break;
					}
				}

				arg0.func.Dispose();
			}

			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OnShouldClose(IntPtr L)
	{
		try
		{
			UniWebView obj = (UniWebView)ToLua.CheckObject(L, 1, typeof(UniWebView));
			EventObject arg0 = null;

			if (LuaDLL.lua_isuserdata(L, 2) != 0)
			{
				arg0 = (EventObject)ToLua.ToObject(L, 2);
			}
			else
			{
				return LuaDLL.luaL_throw(L, "The event 'UniWebView.OnShouldClose' can only appear on the left hand side of += or -= when used outside of the type 'UniWebView'");
			}

			if (arg0.op == EventOp.Add)
			{
				UniWebView.ShouldCloseDelegate ev = (UniWebView.ShouldCloseDelegate)DelegateFactory.CreateDelegate(typeof(UniWebView.ShouldCloseDelegate), arg0.func);
				obj.OnShouldClose += ev;
			}
			else if (arg0.op == EventOp.Sub)
			{
				UniWebView.ShouldCloseDelegate ev = (UniWebView.ShouldCloseDelegate)LuaMisc.GetEventHandler(obj, typeof(UniWebView), "OnShouldClose");
				Delegate[] ds = ev.GetInvocationList();
				LuaState state = LuaState.Get(L);

				for (int i = 0; i < ds.Length; i++)
				{
					ev = (UniWebView.ShouldCloseDelegate)ds[i];
					LuaDelegate ld = ev.Target as LuaDelegate;

					if (ld != null && ld.func == arg0.func)
					{
						obj.OnShouldClose -= ev;
						state.DelayDispose(ld.func);
						break;
					}
				}

				arg0.func.Dispose();
			}

			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OnKeyCodeReceived(IntPtr L)
	{
		try
		{
			UniWebView obj = (UniWebView)ToLua.CheckObject(L, 1, typeof(UniWebView));
			EventObject arg0 = null;

			if (LuaDLL.lua_isuserdata(L, 2) != 0)
			{
				arg0 = (EventObject)ToLua.ToObject(L, 2);
			}
			else
			{
				return LuaDLL.luaL_throw(L, "The event 'UniWebView.OnKeyCodeReceived' can only appear on the left hand side of += or -= when used outside of the type 'UniWebView'");
			}

			if (arg0.op == EventOp.Add)
			{
				UniWebView.KeyCodeReceivedDelegate ev = (UniWebView.KeyCodeReceivedDelegate)DelegateFactory.CreateDelegate(typeof(UniWebView.KeyCodeReceivedDelegate), arg0.func);
				obj.OnKeyCodeReceived += ev;
			}
			else if (arg0.op == EventOp.Sub)
			{
				UniWebView.KeyCodeReceivedDelegate ev = (UniWebView.KeyCodeReceivedDelegate)LuaMisc.GetEventHandler(obj, typeof(UniWebView), "OnKeyCodeReceived");
				Delegate[] ds = ev.GetInvocationList();
				LuaState state = LuaState.Get(L);

				for (int i = 0; i < ds.Length; i++)
				{
					ev = (UniWebView.KeyCodeReceivedDelegate)ds[i];
					LuaDelegate ld = ev.Target as LuaDelegate;

					if (ld != null && ld.func == arg0.func)
					{
						obj.OnKeyCodeReceived -= ev;
						state.DelayDispose(ld.func);
						break;
					}
				}

				arg0.func.Dispose();
			}

			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OnOreintationChanged(IntPtr L)
	{
		try
		{
			UniWebView obj = (UniWebView)ToLua.CheckObject(L, 1, typeof(UniWebView));
			EventObject arg0 = null;

			if (LuaDLL.lua_isuserdata(L, 2) != 0)
			{
				arg0 = (EventObject)ToLua.ToObject(L, 2);
			}
			else
			{
				return LuaDLL.luaL_throw(L, "The event 'UniWebView.OnOreintationChanged' can only appear on the left hand side of += or -= when used outside of the type 'UniWebView'");
			}

			if (arg0.op == EventOp.Add)
			{
				UniWebView.OreintationChangedDelegate ev = (UniWebView.OreintationChangedDelegate)DelegateFactory.CreateDelegate(typeof(UniWebView.OreintationChangedDelegate), arg0.func);
				obj.OnOreintationChanged += ev;
			}
			else if (arg0.op == EventOp.Sub)
			{
				UniWebView.OreintationChangedDelegate ev = (UniWebView.OreintationChangedDelegate)LuaMisc.GetEventHandler(obj, typeof(UniWebView), "OnOreintationChanged");
				Delegate[] ds = ev.GetInvocationList();
				LuaState state = LuaState.Get(L);

				for (int i = 0; i < ds.Length; i++)
				{
					ev = (UniWebView.OreintationChangedDelegate)ds[i];
					LuaDelegate ld = ev.Target as LuaDelegate;

					if (ld != null && ld.func == arg0.func)
					{
						obj.OnOreintationChanged -= ev;
						state.DelayDispose(ld.func);
						break;
					}
				}

				arg0.func.Dispose();
			}

			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UniWebView_OreintationChangedDelegate(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			LuaFunction func = ToLua.CheckLuaFunction(L, 1);

			if (count == 1)
			{
				Delegate arg1 = DelegateFactory.CreateDelegate(typeof(UniWebView.OreintationChangedDelegate), func);
				ToLua.Push(L, arg1);
			}
			else
			{
				LuaTable self = ToLua.CheckLuaTable(L, 2);
				Delegate arg1 = DelegateFactory.CreateDelegate(typeof(UniWebView.OreintationChangedDelegate), func, self);
				ToLua.Push(L, arg1);
			}
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UniWebView_KeyCodeReceivedDelegate(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			LuaFunction func = ToLua.CheckLuaFunction(L, 1);

			if (count == 1)
			{
				Delegate arg1 = DelegateFactory.CreateDelegate(typeof(UniWebView.KeyCodeReceivedDelegate), func);
				ToLua.Push(L, arg1);
			}
			else
			{
				LuaTable self = ToLua.CheckLuaTable(L, 2);
				Delegate arg1 = DelegateFactory.CreateDelegate(typeof(UniWebView.KeyCodeReceivedDelegate), func, self);
				ToLua.Push(L, arg1);
			}
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UniWebView_ShouldCloseDelegate(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			LuaFunction func = ToLua.CheckLuaFunction(L, 1);

			if (count == 1)
			{
				Delegate arg1 = DelegateFactory.CreateDelegate(typeof(UniWebView.ShouldCloseDelegate), func);
				ToLua.Push(L, arg1);
			}
			else
			{
				LuaTable self = ToLua.CheckLuaTable(L, 2);
				Delegate arg1 = DelegateFactory.CreateDelegate(typeof(UniWebView.ShouldCloseDelegate), func, self);
				ToLua.Push(L, arg1);
			}
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UniWebView_MessageReceivedDelegate(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			LuaFunction func = ToLua.CheckLuaFunction(L, 1);

			if (count == 1)
			{
				Delegate arg1 = DelegateFactory.CreateDelegate(typeof(UniWebView.MessageReceivedDelegate), func);
				ToLua.Push(L, arg1);
			}
			else
			{
				LuaTable self = ToLua.CheckLuaTable(L, 2);
				Delegate arg1 = DelegateFactory.CreateDelegate(typeof(UniWebView.MessageReceivedDelegate), func, self);
				ToLua.Push(L, arg1);
			}
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UniWebView_PageErrorReceivedDelegate(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			LuaFunction func = ToLua.CheckLuaFunction(L, 1);

			if (count == 1)
			{
				Delegate arg1 = DelegateFactory.CreateDelegate(typeof(UniWebView.PageErrorReceivedDelegate), func);
				ToLua.Push(L, arg1);
			}
			else
			{
				LuaTable self = ToLua.CheckLuaTable(L, 2);
				Delegate arg1 = DelegateFactory.CreateDelegate(typeof(UniWebView.PageErrorReceivedDelegate), func, self);
				ToLua.Push(L, arg1);
			}
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UniWebView_PageFinishedDelegate(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			LuaFunction func = ToLua.CheckLuaFunction(L, 1);

			if (count == 1)
			{
				Delegate arg1 = DelegateFactory.CreateDelegate(typeof(UniWebView.PageFinishedDelegate), func);
				ToLua.Push(L, arg1);
			}
			else
			{
				LuaTable self = ToLua.CheckLuaTable(L, 2);
				Delegate arg1 = DelegateFactory.CreateDelegate(typeof(UniWebView.PageFinishedDelegate), func, self);
				ToLua.Push(L, arg1);
			}
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UniWebView_PageStartedDelegate(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			LuaFunction func = ToLua.CheckLuaFunction(L, 1);

			if (count == 1)
			{
				Delegate arg1 = DelegateFactory.CreateDelegate(typeof(UniWebView.PageStartedDelegate), func);
				ToLua.Push(L, arg1);
			}
			else
			{
				LuaTable self = ToLua.CheckLuaTable(L, 2);
				Delegate arg1 = DelegateFactory.CreateDelegate(typeof(UniWebView.PageStartedDelegate), func, self);
				ToLua.Push(L, arg1);
			}
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

