//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class WorldMapThumbCameraWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(WorldMapThumbCamera), typeof(Camera2D));
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("m_pWorldMapThumb", get_m_pWorldMapThumb, set_m_pWorldMapThumb);
		L.RegVar("IsCanMoved", get_IsCanMoved, set_IsCanMoved);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_m_pWorldMapThumb(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WorldMapThumbCamera obj = (WorldMapThumbCamera)o;
			WorldMapThumb ret = obj.m_pWorldMapThumb;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index m_pWorldMapThumb on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_IsCanMoved(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WorldMapThumbCamera obj = (WorldMapThumbCamera)o;
			bool ret = obj.IsCanMoved;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index IsCanMoved on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_m_pWorldMapThumb(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WorldMapThumbCamera obj = (WorldMapThumbCamera)o;
			WorldMapThumb arg0 = (WorldMapThumb)ToLua.CheckUnityObject(L, 2, typeof(WorldMapThumb));
			obj.m_pWorldMapThumb = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index m_pWorldMapThumb on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_IsCanMoved(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WorldMapThumbCamera obj = (WorldMapThumbCamera)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.IsCanMoved = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index IsCanMoved on a nil value" : e.Message);
		}
	}
}

