//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class YlyDelegateUtilWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(YlyDelegateUtil), typeof(System.Object));
		L.RegFunction("New", _CreateYlyDelegateUtil);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateYlyDelegateUtil(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				YlyDelegateUtil obj = new YlyDelegateUtil();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: YlyDelegateUtil.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

